{
 "title": "Kubernetes / Compute Resources / Node (Groups)",
 "description": "Grafana dashboard to monitoring nodes grouped by AWS EKS nodegroup. Bear in mind you need a kubernetes label called \"nodegroup\" in each compute < Node Groups",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nodegroup",
    "query": "label_values(kube_node_labels, label_eks_amazonaws_com_nodegroup)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_labels{label_eks_amazonaws_com_nodegroup =~ \"$nodegroup\"}, node)"
   },
   {
    "name": "instance",
    "query": "label_values(kube_pod_info{node =~ \"$node\"}, host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pod Count - Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{exported_namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Pod Count  - Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{exported_namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Pod Count - Not Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{exported_namespace=\"monitoring\"}) - sum(kube_pod_container_status_running{exported_namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(rate(node_cpu_seconds_total{instance=~\"$instance:9100\", mode=\"idle\"}[5m])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$instance:9100\"}[5m])) by (instance))) * 100",
     "legendFormat": "{{instance}}-cpu-utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"}) / node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} * 100",
     "legendFormat": "{{instance}}-memory-utilization"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{instance=~\"$instance:9100\"}) by (instance) - sum (node_filesystem_free_bytes{instance=~\"$instance:9100\"}) by (instance)) / sum (node_filesystem_size_bytes{instance=~\"$instance:9100\"}) by (instance) * 100",
     "legendFormat": "{{kubernetes_node}}-disk-utilization"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$instance:9100\"}[5m]) / (1024 * 1024)) by (instance)",
     "legendFormat": "{{instance}}-read-bytes"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$instance:9100\"}[5m]) / (1024 * 1024)) by (instance)",
     "legendFormat": "{{instance}}-write-bytes"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance:9100\",device=~\"eth.*\"}[2m]) / (1024 * 1024)) by (instance)",
     "legendFormat": "{{instance}}-network-in"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$instance:9100\",device=~\"eth.*\"}[2m]) / (1024 * 1024)) by (instance)",
     "legendFormat": "{{instance}}-network-out"
    }
   ]
  },
  {
   "title": "Load Avg (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Avg (5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"$instance:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Avg (15m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load15{instance=~\"$instance:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}